version: "3.8"

services:
  registry:
    image: registry:2.8.3
    environment:
      # TODO: auth
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_HTTP_SECRET: ${SECRET}
    volumes:
      - registry-data:/var/lib/registry
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.registry.loadbalancer.server.port=5000"
        - "traefik.http.routers.registry.entrypoints=websecure"
        - "traefik.http.routers.registry.tls.certresolver=letsencrypt"
        - "traefik.http.routers.registry.rule=Host(`registry.oliverlambson.com`) || HostRegexp(`^registry\\.?*$$`)"
        - "traefik.http.middlewares.test-auth.basicauth.users=${USERS}"
    healthcheck:
      test: "wget -qO - http://localhost:5000/v2/ || exit 1"
      interval: 4s
      timeout: 2s
      retries: 5
    networks:
      - public

volumes:
  registry-data:

networks:
  public:
    external: true
