entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

api:
  dashboard: false

providers:
  swarm:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /dynamic_conf/
    watch: true
    debugLogGeneratedTemplate: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: oliverlambson@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: web

log:
  level: INFO

accessLog: {}

ping: {}
