http:
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
    gzip-compress:
      compress: {}
    allow-private:
      ipAllowList:
        sourceRange:
          - "127.0.0.1/32"
          - "10.0.0.0/8" # example private network range
    allow-public:
      ipAllowList:
        sourceRange:
          - "0.0.0.0/0"
