http:
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
    gzip-compress:
      compress: {}
    allow-private:
      ipAllowList:
        sourceRange:
          - "127.0.0.1/32" # localhost
          - "10.0.0.0/16" # private network
          - "10.13.13.0/24" # VPN
    allow-public:
      ipAllowList:
        sourceRange:
          - "0.0.0.0/0"
tls:
  stores:
    default:
      defaultGeneratedCert:
        resolver: letsencrypt
        domain:
          main: "www.oliverlambson.com"
          sans:
            - "dummy.oliverlambson.com"
            - "traefik.oliverlambson.com"
            - "dev.oliverlambson.com"
            - "registry.oliverlambson.com"
            - "chat.oliverlambson.com"
