http:
  middlewares:
    forwarded-headers:
      headers:
    https-redirect:
      redirectScheme:
        scheme: https
    gzip-compress:
      compress: {}
    allow-private:
      ipAllowList:
        sourceRange:
          - "127.0.0.1/32" # localhost
          - "10.0.0.0/16" # private network
          - "10.13.13.0/24" # e.g., VPN
    allow-public:
      ipAllowList:
        sourceRange:
          # all internet - TODO: remove once cloudflare proxy works
          - "0.0.0.0/0"
          # cloudflare ipv4
          - 173.245.48.0/20
          - 103.21.244.0/22
          - 103.22.200.0/22
          - 103.31.4.0/22
          - 141.101.64.0/18
          - 108.162.192.0/18
          - 190.93.240.0/20
          - 188.114.96.0/20
          - 197.234.240.0/22
          - 198.41.128.0/17
          - 162.158.0.0/15
          - 104.16.0.0/13
          - 104.24.0.0/14
          - 172.64.0.0/13
          - 131.0.72.0/22
          # cloudflare ipv6
          # - 2400:cb00::/32
          # - 2606:4700::/32
          # - 2803:f800::/32
          # - 2405:b500::/32
          # - 2405:8100::/32
          # - 2a06:98c0::/29
          # - 2c0f:f248::/32

serversTransport:
  forwardedHeaders:
    insecureSkipVerify: true

tls:
  stores:
    default:
      defaultCertificate:
        certFile: /cloudflare/cert.pem
        keyFile: /cloudflare/key.pem
    certificates:
      - certFile: /cloudflare/cert.pem
        keyFile: /cloudflare/key.pem
