name: deploy:dummy

on:
  push:
    branches:
      - main
    paths:
      - "stacks/dummy/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy Stack
        uses: ./.github/actions/deploy-stack
        with:
          name: dummy
          directory: stacks/dummy
          ssh-user: ${{ secrets.VPS_SSH_USER }}
          ssh-host: ${{ secrets.VPS_SSH_HOST }}
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}
