name: deploy:traefik

on:
  push:
    branches:
      - main
    paths:
      - "traefik/**"

jobs:
  deploy:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Stack
        run: |
          scp -r "$service/" "$user@$server:$rootdir/$service/"
          ssh "$user@$server" "docker stack deploy -c $rootdir/$service/compose.yaml $service"
        env:
          user: ${{ secrets.VPS_USER }}
          server: ${{ secrets.VPS_IP }}
          service: traefik
          rootdir: /home/user/gitops
