name: deploy:traefik

on:
  push:
    branches:
      - main
    paths:
      - "stacks/traefik/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy Stack
        uses: ./.github/actions/deploy-stack
        with:
          name: traefik
          directory: stacks/traefik
          ssh-user: ${{ secrets.VPS_SSH_USER }}
          ssh-host: ${{ secrets.VPS_SSH_HOST }}
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}
